services:
  postgres:
    image: postgres:18-alpine
    container_name: freelance_monitor_postgres
    environment:
      POSTGRES_DB: freelance_monitor
      POSTGRES_USER: freelance_monitor
      POSTGRES_PASSWORD: freelance_monitor_password
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8-alpine
    container_name: freelance_monitor_redis
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
