"""create orders table

Revision ID: 67a371498e89
Revises: 
Create Date: 2026-06-17 14:42:41.040442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a371498e89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('budget', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('parsed_budget', sa.Integer(), nullable=True),
    sa.Column('sent_to_telegram', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('contacted', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.Column('matched_keyword', sa.String(), nullable=True),
    sa.Column('negative_keyword', sa.String(), nullable=True),
    sa.Column('risky_keyword', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_orders_source_external_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
